const StockPricesActionTypes = {
  FETCH_STOCK_PRICES_START: 'FETCH_STOCK_PRICES_START',
  FETCH_STOCK_PRICES_SUCCESS: 'FETCH_STOCK_PRICES_SUCCESS',
  FETCH_STOCK_PRICES_FAILURE: 'FETCH_STOCK_PRICES_FAILURE'
};

export default StockPricesActionTypes;
